#!/bin/bash

# This script iterates over files in themes/go-ningen/data/meetups/*.json and
# updates them with the newest data from the Meetup.com API. To add a new
# meetup to the sync, just create a (blank) empty file and run this script to
# fill in the data.
#
# After this step, selected data is saved in /content/meetup/*.md to use with
# the templates in this theme.

set -e
set -o pipefail

cd "$(dirname "$0")/.."

tmpfile=$(mktemp)
curloutput=$(mktemp)

BASE_URL=https://api.meetup.com/Go-ningen/events

for file in data/meetups/*.json; do
    id=$(basename -s ".json" "$file")
    if curl -fsv -o "$tmpfile" "$BASE_URL/$id" &> "$curloutput"; then
        jq . "$tmpfile" > "$file"
    else
        cat "$curloutput"
        rm "$curloutput"
        rm "$tmpfile"
        exit 1
    fi

    case "$(jq -r '.status' "$file")" in
    "upcoming"|"past")
        mdfile=$(printf "../../content/meetup/%d.md" "$id")
        {
            echo '+++'
            printf "id = %d\\n" "$id"
            printf "title = \"%s\"\\n" "$(jq -r '.name' "$file")"
            printf "status = \"%s\"\\n" "$(jq -r '.status' "$file")"
            printf "publishDate = \"%s\"\\n" "$(date -Is -d "@$(jq -r '.created / 1000' "$file")")"
            printf "date = \"%s\"\\n" "$(date -Is -d "@$(jq -r '.time / 1000' "$file")")"
            printf "lastmod = \"%s\"\\n" "$(date -Is -d "@$(jq -r '.updated / 1000' "$file")")"
            echo '+++'
            echo
            echo "Autogenerated, contents not used."
        } > "$mdfile"
        ;;
    esac
done

rm "$tmpfile"
rm "$curloutput"
